### ISSUE TITLE
Add redirect from https://frcteam2984.github.io/ to ljrobotics.org

### ISSUE THREAD

**Issue by rapodaca** [FRCTeam2984/website-old2#101]
Background:

https://stackoverflow.com/questions/5411538/redirect-from-an-html-page

Replace each page at frcteam2984.github.io to the appropriate page on jlrobotics.org. In some cases, we'll have to redirect to the top level ljrobotics.org page because there will be no better option.

The current deploy repository can be found here:

https://github.com/FRCTeam2984/FRCTeam2984.github.io

A Communications team member will need to gain access to this repository to push the needed changes.

**Before this happens, be certain that all content on the old site is available in some form on the new site!**

**Comment by DeputyofDisorder** [comment]
This has been done but I want to wait to see if the pull request is accepted by max
