### ISSUE TITLE
Title Page add last Saturday blog

### ISSUE THREAD

**Issue by DeputyofDisorder** [FRCTeam2984/website-old2#48]
The latest Saturday blog should be on the front page.
Add the latest Saturday blog post:
Saturday 1/6/18

The game has been revealed! The team attended a kickoff at Kearny Mesa High School and the challenge for the First Competition was told to be as such: The game consists of trying to place blocks on a switches to tip it in your favor earning you points while also blocking the enemy team from placing blocks on the switches. The competition also has a raised scale which is in the middle of the field which is 5 feet off the ground! The team can also trade in cubes for “power ups” that benefit the team such as double points, gain control of the switches or scale, etc. each team has “portals” on opposing sides of the field with access to more cubes. All in all there is more than 50 cubes that can be on the field at once each 13 inches. The objective of the game is to get the most amount of points and win the match! This year there are a few ways to earn points and it's now up to our team to find out what way we want to get them!

**Comment by rapodaca** [comment]
Fixed by #44.
