### ISSUE TITLE
Resources Page Add Archetypes

### ISSUE THREAD

**Issue by DeputyofDisorder** [FRCTeam2984/website-old2#54]
Under the Game category add a link to show archetypes.
I made the descriptions a bit fun but made the important text bold to make it easy to quickly look.

Assume that all Archetypes have Autoquest as a goal.
## Blocker:
Two main goals. The **Exchange** and **Blocking**. Ferrying cubes from the Cube Zone to the Exchange to gain the advantage through Powerups in the Vault. Transforms into a bigger robot to constantly blocks attempt to score the Scale. At the end sacrifices the glory to possibly **Raise** two of its **Teammates** to Face the Boss.

Point Analysis/Time Summary:
**Autonomous** - Robot controlled by code
Cross the Autoline-----5 Points------5 seconds
Control Switch----------16 Points----2 seconds to acquire---8 seconds of points
**Teleop** - Robot controlled by Drive team
Exchange deliver 1 cube-----5 Points----------11 seconds
Boost Level 1--------------------20 Points--------10 seconds (Does not require Robot)
Exchange deliver 3 cubes----15 Points--------11 seconds/Powercube load
Force level 3---------------------20 Points--------10 seconds (Does not require Robot)
Exchange deliver 3 cubes----15 Points--------11 seconds/Powercube load
Levitation--------------------------30 Points--------Instant (Requires a Robot with Parked status)
Exchange deliver 2 cubes-----10 Points-------11 seconds/Powercube Load
Block--------------------------------0 Points---------6+ seconds (Whatever time is extra)
Support two robots--------------90 Points 1RP-30 seconds (Coupled with Levitation you get 1 RP by yourself)

If uncontested
**Total Points gained**: 215
**Total Points taken away from Enemy**: 1+ Load

## Heist:
Focuses on one thing. Take. The. **Enemy**. **Switch**. In case of extreme awesomeness can also e tasked with **Blocking**. **Climbs** at the end.

Point Analysis/Time Summary:
**Autonomous**- Robot controlled by code
Cross the Autoline-----5 Points------5 seconds
Control Switch----------16 Points----2 seconds to acquire---8 seconds of points
**Teleop**- Robot controlled by Drive team
Drive to opposite side of field---------0 Points------------5 seconds
Control Enemy Switch------------------0 Points gained--7 seconds
Climb----------------------------------------30 Points----------30 seconds

If uncontested
**Total points gained**: 30 Points
**Total points taken from the enemy**: 135 Points

## Scaler:
Prioritizes the **Scale** giving 1pt per sec to us as well as taking away the opportunity for the enemy to score. To pour salt into the wound will try to gain control of the **Enemy** **Switch**. **Climbs** at the end.

Point Analysis/Time Summary:
**Autonomous** - Robot controlled by code
Cross the Autoline-----5 Points------5 seconds
Control Switch----------16 Points----2 seconds to acquire---8 seconds of points
**Teleop** - Robot controlled by drive team
Control Scale-------------------------135 Points Total with no contest----------------------------15 seconds
Drive to opposite side of field------0 Points----------------------------------------------------------5 seconds
Control Enemy Switch--------------Takes away 1 possible point/second from enemy-----7 seconds
Climb------------------------------------30 Points---------------------------------------------------------30 seconds
If completely uncontested
**Total Points**: 186 Points
**Total Points taken away from enemy**: 135 Points (If contested at scale cannot focus on switch)

## Patroller:
Prioritizes the **Scale** giving 1pt per sec to us as well as taking away the opportunity for the enemy to score. To effectively double our points gains control of our **Switch**. **Climbs** at the end.

Point Analysis/Time Summary:
**Autonomous** - Robot controlled by code
Cross the Autoline-----5 Points------5 seconds
Control Switch----------16 Points----2 seconds to acquire---8 seconds of points
**Teleop** - Robot controlled by drive team
Control Scale--------------------------135 Points Total with no contest----15 seconds/Powercube Load
Drive to opposite side of field------0 Points-----------------------------------5 seconds/Powercube Load
Control  Switch------------------------135 Points Total with no contest----7 seconds/Powercube Load
Climb------------------------------------30 Points----------------------------------30 seconds

  If completely uncontested
**Total Points without Switch**: 186 Points
**Total Points with Switch**: 291 Points (If contested at scale cannot focus on switch)

**Comment by rapodaca** [comment]
This needs estimated point and time summary tables.

**Comment by DeputyofDisorder** [comment]
It has been updated and formatted properly on the website.
