### ISSUE TITLE
HTML validation fails on /sponsors

### ISSUE THREAD

**Issue by rapodaca** [FRCTeam2984/website-old2#89]
See:

https://validator.w3.org/nu/?useragent=Validator.nu%2FLV+http%3A%2F%2Fvalidator.w3.org%2Fservices&acceptlanguage=&doc=http%3A%2F%2Fljrobotics.org%2Fsponsors%2F

It looks like the goal is to use the target="_blank" feature. If so, we must pay attention to HTML validation.

**Comment by DeputyofDisorder** [comment]
This is Lukas' next assignment

**Comment by Hexotical** [comment]
THis can be closed
