### ISSUE TITLE
Team Manual

### ISSUE THREAD

**Issue by rapodaca** [FRCTeam2984/website-old2#90]
Vikings Team Manual should be located at:

`/team-manual/`

A link to it should appear on:

`/resources/`

We may need to re-organize the page for this to make sense. The link currently appears under "General Resources". It might be better to re-label "2984 Training Courses" as "2984 Documentation" then put the link there.

Either way, the currently anchor text ("Vikings Safety Guide") isn't descriptive because the document contains more than safety information.

Team Manual should describe how the team works at a high level.

Safety Guide should be a separate document, appearing under `/safety-guide/`, and focused on general safety guidelines. If there's a document on which the safety test is based, then that might be a good candidate for the Safety Guide.

**Comment by DeputyofDisorder** [comment]
Up to review but I think this is what we want in the Team Manual
