### ISSUE TITLE
Develop a plan to capture video recordings of all San Diego Regional matches

### ISSUE THREAD

**Issue by rapodaca** [FRCTeam2984/website-old2#93]
Last year The Blue Alliance live streamed our matches. None of the recordings are available on the site, but they are available for other teams.

Contact The Blue Alliance (https://www.thebluealliance.com/contact) and:

- find out if it's possible to get our match videos for 2017, 2016 added to the thebluealliance.com site;
- ask how we can ensure that our match videos for 2018 are added to the thebluealliance.com site.

If The Blue Alliance doesn't record videos themselves, ask them how other teams get their videos posted. Then attempt to use similar methods to ensure our matches are recorded.

As a last resort, try to designate a team member/parent as videographer for our matches. This won't be a very good option due to visibility, camera shake. The best option is to figure out how matches are being recorded, then ask whoever does that if we can also get our matches recorded.

**Comment by DeputyofDisorder** [comment]
I have set Niki and Marshall to do this as their next assignment

**Comment by Hexotical** [comment]
Laptop stream to twitch, laptop must have webcam, make sure that the vod option is enabled in the twitch settings. Dowload vod at later date.

**Comment by rapodaca** [comment]
We should start asking local teams competing in the SD regional whether/how they will be capturing videos:

https://www.thebluealliance.com/event/2018casd

If one is planning to do so (or knows how), we should ask them if we can piggyback.

**Comment by Hexotical** [comment]
This issue can be closed
