### ISSUE TITLE
Edit team info on thebluealliance.com

### ISSUE THREAD

**Issue by rapodaca** [FRCTeam2984/website-old2#94]
Remove link to https://frcteam2984.github.io/

Add link to http://ljrobotics.org/

Contact here:

https://www.thebluealliance.com/contact

Remove link to instagram account unless someone on the current team owns it.

**Comment by DeputyofDisorder** [comment]
The link has been added but the instagram account has not been removed yet

**Comment by DeputyofDisorder** [comment]
The new website link is live but the instagram link doesn't go anywhere.
